name: cidadania_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  bootstrap_icons: ^1.11.1
  google_fonts: ^6.1.0
  hexcolor: ^2.0.7
  url_launcher: ^6.1.10
  carousel_images: ^1.1.2
  cupertino_icons: ^1.0.2
  lottie: ^1.4.2
  dio: ^5.3.3
  adaptive_dialog: ^1.9.0+2
  image_picker: ^1.0.4
  image_compression_flutter: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.json