name: cidadania_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bootstrap_icons: ^1.11.1
  google_fonts: ^6.1.0
  hexcolor: ^2.0.7
  cupertino_icons: ^1.0.2
  lottie: ^1.4.2
  dio: ^5.3.3
  adaptive_dialog: ^1.9.0+2
  image_picker: ^1.0.4
  image_compression_flutter: ^1.0.3
  flutter_carousel_widget: ^2.1.2
  url_launcher: ^6.1.14
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  flutter_mobx: ^2.1.1
  mobx: ^2.2.1
  routefly: ^1.0.5
  auto_injector: ^2.0.2
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  mobx_codegen: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.json
    - assets/load.json